// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-ui/lib/aside')['default'];
    ElBacktop: typeof import('element-ui/lib/backtop')['default'];
    ElContainer: typeof import('element-ui/lib/container')['default'];
    ElFooter: typeof import('element-ui/lib/footer')['default'];
    ElHeader: typeof import('element-ui/lib/header')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
