// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-ui/types/alert')['ElAlert'];
    ElAside: typeof import('element-ui/types/aside')['ElAside'];
    ElAutocomplete: typeof import('element-ui/types/autocomplete')['ElAutocomplete'];
    ElAvatar: typeof import('element-ui/types/avatar')['ElAvatar'];
    ElBacktop: typeof import('element-ui/types/backtop')['ElBacktop'];
    ElBadge: typeof import('element-ui/types/badge')['ElBadge'];
    ElBreadcrumb: typeof import('element-ui/types/breadcrumb')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-ui/types/breadcrumb-item')['ElBreadcrumbItem'];
    ElButton: typeof import('element-ui/types/button')['ElButton'];
    ElButtonGroup: typeof import('element-ui/types/button-group')['ElButtonGroup'];
    ElCalendar: typeof import('element-ui/types/calendar')['ElCalendar'];
    ElCard: typeof import('element-ui/types/card')['ElCard'];
    ElCarousel: typeof import('element-ui/types/carousel')['ElCarousel'];
    ElCarouselItem: typeof import('element-ui/types/carousel-item')['ElCarouselItem'];
    ElCascader: typeof import('element-ui/types/cascader')['ElCascader'];
    ElCascaderPanel: typeof import('element-ui/types/cascader-panel')['ElCascaderPanel'];
    ElCheckbox: typeof import('element-ui/types/checkbox')['ElCheckbox'];
    ElCheckboxButton: typeof import('element-ui/types/checkbox-button')['ElCheckboxButton'];
    ElCheckboxGroup: typeof import('element-ui/types/checkbox-group')['ElCheckboxGroup'];
    ElCol: typeof import('element-ui/types/col')['ElCol'];
    ElCollapse: typeof import('element-ui/types/collapse')['ElCollapse'];
    ElCollapseItem: typeof import('element-ui/types/collapse-item')['ElCollapseItem'];
    ElColorPicker: typeof import('element-ui/types/color-picker')['ElColorPicker'];
    ElContainer: typeof import('element-ui/types/container')['ElContainer'];
    ElDatePicker: typeof import('element-ui/types/date-picker')['ElDatePicker'];
    ElDescriptions: typeof import('element-ui/types/descriptions')['ElDescriptions'];
    ElDescriptionsItem: typeof import('element-ui/types/descriptions-item')['ElDescriptionsItem'];
    ElDialog: typeof import('element-ui/types/dialog')['ElDialog'];
    ElDivider: typeof import('element-ui/types/divider')['ElDivider'];
    ElDrawer: typeof import('element-ui/types/drawer')['ElDrawer'];
    ElDropdown: typeof import('element-ui/types/dropdown')['ElDropdown'];
    ElDropdownItem: typeof import('element-ui/types/dropdown-item')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-ui/types/dropdown-menu')['ElDropdownMenu'];
    ElEmpty: typeof import('element-ui/types/empty')['ElEmpty'];
    ElFooter: typeof import('element-ui/types/footer')['ElFooter'];
    ElForm: typeof import('element-ui/types/form')['ElForm'];
    ElFormItem: typeof import('element-ui/types/form-item')['ElFormItem'];
    ElHeader: typeof import('element-ui/types/header')['ElHeader'];
    ElIcon: typeof import('element-ui/types/icon')['ElIcon'];
    ElImage: typeof import('element-ui/types/image')['ElImage'];
    ElInput: typeof import('element-ui/types/input')['ElInput'];
    ElInputNumber: typeof import('element-ui/types/input-number')['ElInputNumber'];
    ElLink: typeof import('element-ui/types/link')['ElLink'];
    ElMain: typeof import('element-ui/types/main')['ElMain'];
    ElMenu: typeof import('element-ui/types/menu')['ElMenu'];
    ElMenuItem: typeof import('element-ui/types/menu-item')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-ui/types/menu-item-group')['ElMenuItemGroup'];
    ElMessage: typeof import('element-ui/types/message')['ElMessageComponent'];
    ElMessageBox: typeof import('element-ui/types/message-box')['ElMessageBoxComponent'];
    ElNotification: typeof import('element-ui/types/notification')['ElNotificationComponent'];
    ElOption: typeof import('element-ui/types/option')['ElOption'];
    ElOptionGroup: typeof import('element-ui/types/option-group')['ElOptionGroup'];
    ElPageHeader: typeof import('element-ui/types/page-header')['ElPageHeader'];
    ElPagination: typeof import('element-ui/types/pagination')['ElPagination'];
    ElPopconfirm: typeof import('element-ui/types/popconfirm')['ElPopconfirm'];
    ElPopover: typeof import('element-ui/types/popover')['ElPopover'];
    ElProgress: typeof import('element-ui/types/progress')['ElProgress'];
    ElRadio: typeof import('element-ui/types/radio')['ElRadio'];
    ElRadioButton: typeof import('element-ui/types/radio-button')['ElRadioButton'];
    ElRadioGroup: typeof import('element-ui/types/radio-group')['ElRadioGroup'];
    ElRate: typeof import('element-ui/types/rate')['ElRate'];
    ElResult: typeof import('element-ui/types/result')['ElResult'];
    ElRow: typeof import('element-ui/types/row')['ElRow'];
    ElSelect: typeof import('element-ui/types/select')['ElSelect'];
    ElSkeleton: typeof import('element-ui/types/skeleton')['ElSkeleton'];
    ElSkeletonItem: typeof import('element-ui/types/skeleton-item')['ElSkeletonItem'];
    ElSlider: typeof import('element-ui/types/slider')['ElSlider'];
    ElSpinner: typeof import('element-ui/types/spinner')['ElSpinner'];
    ElStep: typeof import('element-ui/types/step')['ElStep'];
    ElSteps: typeof import('element-ui/types/steps')['ElSteps'];
    ElSubmenu: typeof import('element-ui/types/submenu')['ElSubmenu'];
    ElSwitch: typeof import('element-ui/types/switch')['ElSwitch'];
    ElTable: typeof import('element-ui/types/table')['ElTable'];
    ElTableColumn: typeof import('element-ui/types/table-column')['ElTableColumn'];
    ElTabPane: typeof import('element-ui/types/tab-pane')['ElTabPane'];
    ElTabs: typeof import('element-ui/types/tabs')['ElTabs'];
    ElTag: typeof import('element-ui/types/tag')['ElTag'];
    ElTimeline: typeof import('element-ui/types/timeline')['ElTimeline'];
    ElTimelineItem: typeof import('element-ui/types/timeline-item')['ElTimelineItem'];
    ElTimePicker: typeof import('element-ui/types/time-picker')['ElTimePicker'];
    ElTimeSelect: typeof import('element-ui/types/time-select')['ElTimeSelect'];
    ElTooltip: typeof import('element-ui/types/tooltip')['ElTooltip'];
    ElTransfer: typeof import('element-ui/types/transfer')['ElTransfer'];
    ElTree: typeof import('element-ui/types/tree')['ElTree'];
    ElUpload: typeof import('element-ui/types/upload')['ElUpload'];
    VIcon: typeof import('@iconify/vue2')['Icon'];
  }
}

export {};
